ULMFIT with fastai-v1
maaario/nlp-slovak-universal-language-model pull request #10
Opened 2019-06-21 12:37 UTC by maaario

now only to show you my progress on data processing and model pre-training

2019-06-21 14:09 UTC, buj commented
### main.py

`prepare_lm_dataset`: I believe it either does not tokenize the input at all, or it uses some default tokenizer (i.e. for english language). So when creating the TextLMDataBunch we should pass it `tokenizer=Tokenizer(lang = "xx")` or something like that (`xx` stands for any obscure language, and slovak language is an obscure language).

`prepare_clas_dataset`: Same as above.

Minor note: one need not pass `test_df=None`, it is `None` by default.

### util.py

`evaluate_perplexity`: I highly suspect that it is possible to calculate perplexity simply by evaluating the model on the dataset with an appropriate loss function. See [this link](https://en.wikipedia.org/wiki/Perplexity#Perplexity_of_a_probability_model)---it is merely `e**cross_entropy`, so it should be easy to calculate using cross-entropy loss. The loss can be obtained using [`Learner.validate(...)`](https://docs.fast.ai/basic_train.html#Learner.validate).

### Other remarks

Currently the learner does not use CUDA (?). The model will sit on the same device as the dataset's (or rather databunch's) device, which is currently CPU (there is no flag to set it otherwise). There are two ways to alter this behaviour:
- Work with [`DeviceDataLoader`](https://docs.fast.ai/basic_data.html#DeviceDataLoader)s, but this is a big step away from what is currently implemented. Currently we load the data directly through pandas; to use the DeviceDataLoader, one must first construct a Pytorch [`DataLoader`](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).
- When constructing the databunch from pandas dataframe, one can pass the argument `device = (some torch device)`. (This is not obvious from the documentation, but should work---`from_df` internally uses `DataBunch.create` and it passes keyword arguments to that constructor.)

2019-06-21 14:17 UTC, buj reviewed
### Other remarks

Currently the learner does not use CUDA (?). The model will sit on the same device as the dataset's (or rather databunch's) device, which is currently CPU (there is no flag to set it otherwise). There are two ways to alter this behaviour:
- Work with [`DeviceDataLoaders`](https://docs.fast.ai/basic_data.html#DeviceDataLoader), but this is a big step away from what is currently implemented. Currently we load the data directly through pandas; to use the DeviceDataLoader, one must first construct a Pytorch [`DataLoader`](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).
- When constructing the databunch from pandas dataframe, one can pass the argument device = (some torch device). (This is not obvious from the documentation, but should work---from_df internally uses [`DataBunch.create`](https://docs.fast.ai/basic_data.html#DataBunch.create) and it passes keyword arguments to that constructor.)

2019-06-21 14:17 UTC, buj commented on ulmfit-fastai-v1/main.py
> +def prepare_lm_dataset(input_path, output_dir, valid_split=0.2, min_freq=2):
I believe it either does not tokenize the input at all, or it uses some default tokenizer (i.e. for english language). So when creating the `TextLMDataBunch` we should pass it `tokenizer=Tokenizer(lang = "xx")` or something like that (`xx` stands for any obscure language, and slovak language is an obscure language).

2019-06-21 14:17 UTC, buj commented on ulmfit-fastai-v1/main.py
> +def prepare_clas_dataset(input_path, output_dir, valid_split=0.2):
Same as above.

2019-06-21 14:17 UTC, buj commented on ulmfit-fastai-v1/main.py
> +        output_dir, train_df, valid_df, test_df=None, vocab=data_finetune_lm.train_ds.vocab, bs=32)
Minor note: one need not pass `test_df=None`, it is `None` by default.

2019-06-21 14:17 UTC, buj commented on ulmfit-fastai-v1/utils.py
> +def evaluate_perplexity(learner, text):
I highly suspect that it is possible to calculate perplexity simply by evaluating the model on the dataset with an appropriate loss function. See this link---it is merely `e**cross_entropy`, so it should be easy to calculate using cross-entropy loss. The loss can be obtained using [`Learner.validate(...)`](https://docs.fast.ai/basic_train.html#Learner.validate).

2019-06-22 12:42 UTC, maaario commented on ulmfit-fastai-v1/main.py
> +def prepare_lm_dataset(input_path, output_dir, valid_split=0.2, min_freq=2):
Thanks. By defualt english tokenizer is used, but we can switch to xx as you described. This will make tokenization more explicite and we can potentially tweak our own tokenizer in the future.

2019-06-22 12:47 UTC, maaario commented on ulmfit-fastai-v1/main.py
> +def prepare_clas_dataset(input_path, output_dir, valid_split=0.2):
fixed

2019-06-22 12:47 UTC, maaario commented on ulmfit-fastai-v1/main.py
> +        output_dir, train_df, valid_df, test_df=None, vocab=data_finetune_lm.train_ds.vocab, bs=32)
thanks, fixed

2019-06-22 15:06 UTC, maaario commented on ulmfit-fastai-v1/utils.py
> +def evaluate_perplexity(learner, text):
Now we use e**loss as the main perplexity estimate, but I also kept our perplexity computation, because we can control it well.

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +import sys, fire
split to separate imports - fire to 2nd group (3rd party)

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +from utils import *
put utils to separate import group as it is our local library

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +def finetune_lm(data_dir, model_dir, cyc_len = 25, lr = 4e-3, lr_factor = 1/2.6):
PEP8 - no spaces around "=" in function headers, add spaces around operator "/"

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +    techniques from ULMFIT paper (Discriminative fine-tuning, Slanted
As our whole project is based on ULMFIT, this is unnecessary here.

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +    <cyc_len>: cycle length (also the number of epochs -- only 1 cycle is done)
pls explain better

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +    awd_lstm_lm_config = dict(
load hparams from json, as it was added to main.py

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +    learner.model_dir = ""
add new parameter - dir for the finetuned model and save the encoder there instead of using this current local path

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +    lrs = [lr * lr_factor**i for i in range(num_layers)][::-1]
pep8 - spaces around **

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/finetune_lm.py
> +    learner.fit_one_cycle(cyc_len = cyc_len, max_lr = lrs, div_factor = 32, pct_start = 0.1)
pep8 - no spaces around = in kwargs

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/train_clas.py
> +import sys, fire
Tidy up imports as above

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/train_clas.py
> +def train_clas(data_dir, model_dir, cyc_len = 1, lr = 4e-3, lr_factor = 1/2.6):
pep8 - as above

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/train_clas.py
> +    awd_lstm_lm_config = dict(
load config from json

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/train_clas.py
> +    learner.model_dir = ""
provide path for classifier model as parameter

2019-06-22 16:51 UTC, maaario commented on ulmfit-fastai-v1/train_clas.py
> +    lrs = [lr * lr_factor**i for i in range(num_layers)][::-1]
pep8 - no spaces around **

2019-06-23 10:22 UTC, buj commented on ulmfit-fastai-v1/train_clas.py
> +    lrs = [lr * lr_factor**i for i in range(num_layers)][::-1]
PEP8 actually has no problem with this, I also believe it does not hinder readability.

2019-06-23 10:22 UTC, buj commented on ulmfit-fastai-v1/train_clas.py
> +    awd_lstm_lm_config = dict(
done

2019-06-23 10:22 UTC, buj commented on ulmfit-fastai-v1/train_clas.py
> +def train_clas(data_dir, model_dir, cyc_len = 1, lr = 4e-3, lr_factor = 1/2.6):
done

2019-06-23 10:23 UTC, buj commented on ulmfit-fastai-v1/train_clas.py
> +import sys, fire
done

2019-06-23 10:23 UTC, buj commented on ulmfit-fastai-v1/finetune_lm.py
> +    <cyc_len>: cycle length (also the number of epochs -- only 1 cycle is done)
should be more in-detail now

2019-06-23 10:23 UTC, buj commented on ulmfit-fastai-v1/finetune_lm.py
> +    techniques from ULMFIT paper (Discriminative fine-tuning, Slanted
removed

2019-06-23 10:23 UTC, buj commented on ulmfit-fastai-v1/finetune_lm.py
> +def finetune_lm(data_dir, model_dir, cyc_len = 25, lr = 4e-3, lr_factor = 1/2.6):
spaces around "=" removed, spaces around "/" are not mandated by PEP8.

2019-06-23 10:24 UTC, buj commented on ulmfit-fastai-v1/finetune_lm.py
> +from utils import *
done

2019-06-23 10:24 UTC, buj commented on ulmfit-fastai-v1/finetune_lm.py
> +import sys, fire
done

2019-06-23 10:39 UTC, buj commented on ulmfit-fastai-v1/train_clas.py
> +    learner.model_dir = ""
done

2019-06-23 16:06 UTC, adam-dej requested changes
Generally I like this re-write. It would be nice to extend the README to include expected formats of inputs, and to describe the structure of files that are being saved to model folders (file names, types, purposes, how to load them outside of our pipeline if needed, …)

I'm sorry that most of my comments are coding style nitpicks. Some of those comments apply to multiple files, but I've written them only once (such as hardcoded tokenizer language code or `os.path` vs Pathlib usage). Please take care to fix all occurences.

2019-06-23 16:06 UTC, adam-dej commented on ulmfit-fastai-v1/README.md
> +
It would be nice to also explicitly describe workflows for scenarios in which I don't want to use pre-trained model when fine-tuning, or I want to train model from scratch during classifier training. Legacy pipeline has these options, and it would help us with our goal - determining the added value of fine-tuning a pre-trained model.

2019-06-26 08:49 UTC, adam-dej requested changes

2019-06-26 08:49 UTC, adam-dej commented on ulmfit-fastai-v1/train_lm.py
> +        pretrained (bool): If `pretrained` is set, a trained model is first loaded from `model_dir`
I believe that renaming this param to `use_pretrained_lm` would help avoid confusion.

2019-06-26 08:49 UTC, adam-dej commented on ulmfit-fastai-v1/train_lm.py
> +        hparam_updates (dict): A dictionary with updates of model hyper-parametrs. By default,
A link to fastai docs explaining available options in this dict would be helpful.

2019-06-26 09:42 UTC, maaario commented on ulmfit-fastai-v1/train_lm.py
> +        pretrained (bool): If `pretrained` is set, a trained model is first loaded from `model_dir`
ok, I renamed it

2019-06-26 09:43 UTC, maaario commented on ulmfit-fastai-v1/train_lm.py
> +        hparam_updates (dict): A dictionary with updates of model hyper-parametrs. By default,
a link to code with model is now provided

2019-06-26 09:45 UTC, adam-dej approved these changes

2019-06-26 09:57 UTC, merged